// These are all the fake replies shown to the user in the private chat.
// They are stored locally and never sent to a server or processed by AI.
// They are intentionally calm, de-escalating, and non-judgmental.
export const FAKE_REPLIES: string[] = [
  "Keep going. This is staying here.",
  "You don't have to make this message polite right now.",
  "Better here than sent in the heat of the moment.",
  "That sounds heavy. Put the raw version here first.",
  "No one will receive this.",
  "You can delete this when you're ready.",
  "This is just the draft your emotions needed.",
  "Let it out here. Decide later.",
  "You're allowed to pause before replying.",
  "This chat disappears when you delete it.",
  "Say what you need to say. No one's listening.",
  "There's no wrong thing to write here.",
  "Typing it out is different from sending it.",
  "This space won't judge you.",
  "Write it all. Then decide what to do with it.",
  "The raw version belongs here, not in a sent message.",
  "This version stays with you.",
  "Sometimes writing it is enough.",
  "Nothing you type here leaves this screen.",
  "You're in control of what happens next.",
  "Take your time.",
  "Say the part you'd usually hold back.",
  "This is the one place you don't have to edit yourself.",
  "The draft nobody else will read.",
  "Write until you feel like stopping.",
  "You don't have to be calm here.",
  "This is not going anywhere.",
  "The unfiltered version belongs here.",
  "Say it all before you decide what to send.",
  "Every word stays exactly where you put it.",
  "Nothing leaves. Keep going.",
  "This is a space just for you.",
  "You don't have to explain yourself here.",
  "Write it out. See how it feels.",
  "The first draft is always the most honest.",
  "Write the version you need, not the version they'll see.",
  "This disappears completely when you're ready.",
  "Your words are safe here.",
  "Write without censoring yourself.",
  "The unedited version lives here.",
  "Nobody reads this but you.",
  "Get it out of your head and onto the screen.",
  "This is just between you and the void.",
  "Let the pressure out here.",
  "You can say exactly how you feel.",
  "This chat won't hold it against you.",
  "Nothing here can be screenshot and shared.",
  "When you delete it, it's truly gone.",
  "This is the message that never gets sent.",
  "You're safe to write the real version here.",
  "The only audience is you.",
  "Writing it down can help you see it more clearly.",
  "Sometimes the most important messages are the ones you don't send.",
  "This is a pause. A private one.",
  "A few minutes here might save you from a message you'd regret.",
  "No judgment. No consequences. Just words.",
  "You can keep going. None of this is going anywhere.",
  "The Void is here. Say whatever you need to say.",
  "Dump it all here first. You can edit later.",
];
